### PR TITLE
gps_failure

### PR DESCRIPTION
**Pull request by aswath1**
# PR Details
## Description
The Health monitor in develop is missing the logic or not evaluating the "s_1_l1_1_l2_1_g_0" which denotes GPS failure only.

## Related Issue
https://github.com/usdot-fhwa-stol/carma-platform/issues/675

## How Has This Been Tested?
Unit tested

## Types of changes

- [x ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [x ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](Contributing.md) 
- [x ] I have added tests to cover my changes.
- [x ] All new and existing tests passed.

### CODE REVIEW

**Comment by maefromm** [comment]
@aswath1  would you please post the result of the unit test here, I would appreciate it. Thanks!

**Comment by aswath1** [comment]
Result of the unit test 

Caution
GPS Failed

**Comment by maefromm** [comment]
@aswath1 sorry I meant the actual screenshot of the terminal after you run the unit test in your VM.

**Comment by aswath1** [comment]
image

**Comment by maefromm** [comment]
@aswath1 thank you! I will merge once the checks have passed.

**Pull request merged**
