### PR TITLE
CARMAPlatform - Fix "Autoware" plugin to be named "Cruising" Plugin

### PR DESCRIPTION
**Pull request by dan-du-car**
# PR Details
## Description
The Autoware Plugin is currently showing on UI. Per discussion with @TonysCousin this should be renamed to Cruising Plugin.

This includes renaming the folder and files under autoware_plugin to cruising_plugin.

## Related Issue
https://github.com/usdot-fhwa-stol/carma-platform/issues/915

## Motivation and Context
ACE Demo Release.

## How Has This Been Tested?
Local integration testing
Integration testing in Pacifica vehicle

## Types of changes
C++ 

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [x] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by dan-du-car** [comment]
Should this checkout.sh be updated to release/wonderer? https://github.com/usdot-fhwa-stol/carma-platform/blob/d78c755354c73e64970b781ac01c8298009c11b2/docker/checkout.bash#L40

**Comment by maefromm** [comment]
> Should this checkout.sh be updated to release/wonderer?
> 
> https://github.com/usdot-fhwa-stol/carma-platform/blob/d78c755354c73e64970b781ac01c8298009c11b2/docker/checkout.bash#L40

No, i don't think so. For the candidate branches, we actually build it as release mode, not develop mode.

**Comment by maefromm** [comment]
@dan-du-car i think we should integration test before we merge, let's see when one of us can do this.

**Comment by dan-du-car** [comment]
> @dan-du-car i think we should integration test before we merge, let's see when one of us can do this.

@maefromm I did the integration test in local. In vehicle test, training required.

**Comment by maefromm** [comment]
@dan-du-car found reference to autoware plugin in the health monitor unit test. May want to update this.

**Comment by maefromm** [comment]
Please search for "autoware_" in your branch under carma-platform, and i've found these 3 files with 23 matches  that I think should be updated: 
image

image

image

**Comment by dan-du-car** [comment]
@maefromm autoware_ is addressed

**Review by msmcconnell — APPROVED** [review]

**Review by maefromm — APPROVED** [review]

**Comment by dan-du-car** [comment]
sonar coverage doesn't work when targeted at branches not on develop

**Comment by dan-du-car** [comment]
This branch has been pulled and integration tested in Pacifica vehicle

**Pull request merged**
